name: Swift for Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Prepare build environment, then Build swift
      run: |
        sudo apt-get install libicu-dev libpython2.7 libpython2.7-dev
        mkdir Swift_For_Ubuntu
        cd Swift_For_Ubuntu
        curl -O https://swift.org/builds/swift-5.1.3-release/ubuntu1804/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
        tar -zxvf swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
        cd swift-5.1.3-RELEASE-ubuntu18.04
        export SWIFT_FOR_UBUNTU=`pwd`
        echo $SWIFT_FOR_UBUNTU
        export PATH="${SWIFT_FOR_UBUNTU}"/usr/bin:"${PATH}"
        echo $PATH
        echo "export PATH=/usr/share/swift/usr/bin:$PATH" >> ~/.bashrc
        source  ~/.bashrc
        cd ../..
        swift build -v

    - name: Run integration tests
      run: ./build_then_upload.sh "nightly-ubuntu"
      env:
        PUBLISH_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
