name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Change xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.1.app/Contents/Developer'

    - name: Build
      run: swift build -v
    - name: Run unit tests
      run: swift test -v
    - name: Run integration tests
      run: ./build_then_upload.sh "nightly"
      env:
        PUBLISH_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
    - name: Upload stable binary
      run: |
        VERSION=`echo ${GITHUB_REF//refs\/tags\//}`
        ./build_then_upload.sh $VERSION
        sleep 5
        ./draft_to_release.sh $VERSION
      env:
        PUBLISH_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      if: contains(github.ref, 'tags/v')
